# Juniper SRX Vulnerability Monitoring Configuration
# IT Security Specialist - ISP/NOC

# Router Configuration
routers:
  - name: "SRX-01"
    ip: "192.168.1.1"
    username: "admin"
    model: "SRX3400"
    junos_version: "20.2R3-S2.5"
    location: "Primary DC"
    critical: true
    
  - name: "SRX-02" 
    ip: "192.168.1.2"
    username: "admin"
    model: "SRX3400"
    junos_version: "20.2R3-S2.5"
    location: "Secondary DC"
    critical: true
    
  - name: "SRX-03"
    ip: "192.168.1.3"
    username: "admin"
    model: "SRX1500"
    junos_version: "20.2R3-S2.5"
    location: "Edge POP"
    critical: false

# Monitoring Settings
monitoring:
  scan_interval_hours: 6
  security_advisory_check_interval_hours: 2
  configuration_backup_interval_hours: 24
  vulnerability_scan_timeout: 300
  max_concurrent_scans: 5

# Alert Configuration
alerts:
  email:
    enabled: true
    smtp_server: "smtp.company.com"
    smtp_port: 587
    from_address: "security@company.com"
    to_addresses: ["noc@company.com", "security@company.com"]
  
  slack:
    enabled: false
    webhook_url: ""
    channel: "#security-alerts"
  
  severity_levels:
    critical: ["email", "slack"]
    high: ["email"]
    medium: ["email"]
    low: []

# Vulnerability Sources
vulnerability_sources:
  juniper_security_advisories: true
  cve_database: true
  nist_nvd: true
  juniper_psirt: true

# Reporting
reporting:
  daily_report: true
  weekly_summary: true
  monthly_compliance: true
  report_retention_days: 90
  output_format: ["html", "pdf", "excel"]

# Security Compliance
compliance:
  check_configuration_changes: true
  verify_firmware_integrity: true
  monitor_user_accounts: true
  audit_logging: true
  backup_verification: true
